CREATE TABLE EMP
 (EMPNO NUMERIC(4) primary key,
 ENAME VARCHAR(10),
 JOB VARCHAR(9),
 MGR NUMERIC(4),
 HIREDATE DATE,
 SAL NUMERIC(7,2),
 COMM NUMERIC(7,2),
 DEPTNO NUMERIC(2));
 grant all on emp to scott;
 